import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {createContactHandler} from '../api/contact.js';
const valid={name:' Reader ',email:'Reader@Example.com',reason:'story-suggestion',message:'A local cultural story worth exploring.',contributor:'yes',consent:'yes'};
const saved=[];
const handler=createContactHandler({configured:()=>true,save:async(path,record)=>saved.push({path,record})});
const req=(data=valid,origin='https://www.folkly.com')=>new Request('https://www.folkly.com/api/contact',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(data)});
assert.equal((await handler(req())).status,200);
assert.equal(saved[0].record.email,'reader@example.com');assert.equal(saved[0].record.name,'Reader');assert.equal(saved[0].record.contributor,true);assert.match(saved[0].path,/^contacts\/[a-f0-9]{64}\.json$/);
await handler(req());assert.equal(saved[0].path,saved[1].path);
for(const change of [{name:''},{email:'bad'},{email:'<script>@x.com'},{reason:'unknown'},{message:'short'},{message:'x'.repeat(3001)},{consent:'no'},{contributor:'false'},{website:'spam'}])assert.equal((await handler(req({...valid,...change}))).status,400);
assert.equal((await handler(req(valid,'https://other.example'))).status,403);
assert.equal((await handler(req(valid,''))).status,403);
assert.equal((await handler(new Request('https://www.folkly.com/api/contact'))).status,405);
assert.equal((await handler(req({...valid,message:'x'.repeat(9000)}))).status,413);
assert.equal(saved.length,2);
const off=createContactHandler({configured:()=>false,save:()=>assert.fail('write while off')});assert.equal((await off(req())).status,503);
const failed=createContactHandler({configured:()=>true,save:()=>{throw Error('private credential detail');}});const response=await failed(req());assert.equal(response.status,503);assert(!(await response.text()).includes('credential'));
const noContributor={...valid,reason:'contributing'};delete noContributor.contributor;await handler(req(noContributor));assert.equal(saved.at(-1).record.contributor,true);
// Browser form only resets after confirmed durable success; uses textContent, no HTML.
let submit,resetCount=0,resolve;
const button={disabled:false},status={textContent:''};
const form={addEventListener:(name,fn)=>{submit=fn;},querySelector:()=>button,reset:()=>resetCount++};
const document={querySelector:selector=>selector==='#contact-form'?form:status};
const context={document,FormData:class{*[Symbol.iterator](){yield ['name','Reader'];}},fetch:()=>new Promise(r=>{resolve=r;})};
vm.runInNewContext(await readFile('web/vercel/contact.js','utf8'),context);
let work=submit({preventDefault(){}});assert.equal(button.disabled,true);assert.equal(resetCount,0);
resolve({ok:false,json:async()=>({message:'Unavailable'})});await work;assert.equal(resetCount,0);assert.equal(button.disabled,false);
work=submit({preventDefault(){}});resolve({ok:true,json:async()=>({message:'Saved'})});await work;assert.equal(resetCount,1);assert.equal(status.textContent,'Saved');
const html=await readFile('dist/about.html','utf8');assert(html.includes('Folkly is seeking contributors'));assert(html.includes('name="reason"'));assert(html.includes('name="contributor"'));assert(html.includes('role="status"'));assert(html.includes('/contact.js'));assert(!html.includes('BLOB_READ_WRITE_TOKEN'));
console.log('Contact checks passed: private bounded records, contribution intent, repeat deduplication, validation, origin/method/honeypot, outage redaction, durable-success UI timing and About form build.');

const {readContactInbox}=await import('../server/contact-inbox.js');
const env={BLOB_STORE_ID:'fixture'};
const storage={list:async args=>{assert.deepEqual(args,{prefix:'contacts/',limit:20});return {blobs:[{pathname:saved[0].path,size:1024}],hasMore:true,cursor:'page2'};},get:async(path,args)=>{assert.deepEqual(args,{access:'private',useCache:false});return {statusCode:200,stream:new Response(JSON.stringify(saved[0].record)).body};}};
const inbox=await readContactInbox({env,storage});assert.equal(inbox.available,true);assert.equal(inbox.hasMore,true);assert.equal(inbox.rows[0].email,'reader@example.com');assert(!JSON.stringify(inbox).includes('contacts/'));
assert.equal((await readContactInbox({env:{},storage:{list:()=>assert.fail('unconfigured access')}})).available,false);
assert.equal((await readContactInbox({env,storage:{list:async()=>{throw Error('secret');}}})).available,false);
assert.equal((await readContactInbox({env,storage:{...storage,list:async()=>({blobs:[{pathname:'subscribers/private.json',size:1}]})}})).available,false);
const invalidEmailStorage={...storage,get:async()=>({statusCode:200,stream:new Response(JSON.stringify({...saved[0].record,email:'javascript:alert(1)'})).body})};
assert.equal((await readContactInbox({env,storage:invalidEmailStorage})).available,false);
console.log('Owner inbox checks passed: bounded private prefix/read, field allowlist, no blob links, missing configuration and provider failure holds.');

assert.equal(inbox.nextCursor,'page2');
let pageRead=0;
const pageStorage={...storage,list:async args=>{pageRead++;assert.equal(args.cursor,'page2');return {blobs:[],hasMore:false};}};
assert.equal((await readContactInbox({env,storage:pageStorage,cursor:'page2'})).nextCursor,null);
assert.equal((await readContactInbox({env,storage:pageStorage,cursor:'bad\nvalue'})).available,false);assert.equal(pageRead,1);
assert.equal((await readContactInbox({env,storage:pageStorage,cursor:'x'.repeat(2049)})).available,false);assert.equal(pageRead,1);
assert.equal((await readContactInbox({env,storage,cursor:'page2'})).available,false);
