-- Prepared Folkly Postgres migration. Apply only to the verified Folkly project.
-- Text JSON and timestamps preserve the existing version/evidence digest representation.
BEGIN;
CREATE TABLE public.folkly_article_versions (
  id TEXT PRIMARY KEY,
  article_id TEXT NOT NULL,
  version INTEGER NOT NULL,
  content_json TEXT NOT NULL,
  created_by TEXT NOT NULL,
  note TEXT,
  created_at TEXT NOT NULL,
  UNIQUE(article_id, version)
);

CREATE TABLE public.folkly_articles (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  deck TEXT,
  persona_id TEXT,
  byline_legacy TEXT,
  place_label TEXT,
  country TEXT,
  category TEXT,
  status TEXT NOT NULL DEFAULT 'draft',
  word_count INTEGER,
  reading_minutes INTEGER,
  is_cover INTEGER NOT NULL DEFAULT 0,
  home_position INTEGER,
  home_short TEXT,
  home_place TEXT,
  home_eyebrow TEXT,
  home_dek TEXT,
  home_figure_src TEXT,
  home_figure_alt TEXT,
  home_figure_style TEXT,
  home_figure_w TEXT,
  home_figure_h TEXT,
  next_story_slug TEXT,
  content_hash TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
, pipeline_state TEXT NOT NULL DEFAULT 'pitch', revision_attempts INTEGER NOT NULL DEFAULT 0, hold_reason TEXT, score DOUBLE PRECISION, score_reason TEXT);

CREATE TABLE public.folkly_assignments (
  id TEXT PRIMARY KEY,
  pitch_id TEXT,
  persona_id TEXT,
  article_id TEXT,
  slot_date TEXT,
  reason TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE public.folkly_audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at TEXT NOT NULL,
  actor TEXT NOT NULL,
  action TEXT NOT NULL,
  entity TEXT,
  entity_id TEXT,
  reason TEXT
);

CREATE TABLE public.folkly_claim_citations (
  id TEXT PRIMARY KEY,
  article_version_id TEXT NOT NULL,
  claim TEXT NOT NULL,
  source_ids TEXT NOT NULL DEFAULT '[]',
  kind TEXT NOT NULL DEFAULT 'fact',
  verified INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE public.folkly_editorial_checks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_version_id TEXT NOT NULL,
  check_name TEXT NOT NULL,
  check_type TEXT NOT NULL,
  result TEXT NOT NULL,
  details TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE public.folkly_job_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id TEXT NOT NULL,
  step_name TEXT NOT NULL,
  status TEXT NOT NULL,
  attempt INTEGER NOT NULL DEFAULT 1,
  detail TEXT,
  at TEXT NOT NULL
);

CREATE TABLE public.folkly_jobs (
  id TEXT PRIMARY KEY,
  job_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  attempt INTEGER NOT NULL DEFAULT 0,
  next_run_at TEXT,
  last_run_at TEXT,
  error TEXT
);

CREATE TABLE public.folkly_media_assets (
  id TEXT PRIMARY KEY,
  file_path TEXT NOT NULL UNIQUE,
  original_url TEXT,
  creator TEXT,
  license TEXT,
  license_url TEXT,
  attribution TEXT,
  downloaded_at TEXT,
  sha256 TEXT,
  caption TEXT,
  alt_text TEXT,
  asset_kind TEXT NOT NULL DEFAULT 'photo',
  notes TEXT
);

CREATE TABLE public.folkly_page_blocks (
  slug TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  meta_description TEXT,
  main_html TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE public.folkly_persona_briefs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_id TEXT NOT NULL,
  version INTEGER NOT NULL,
  brief_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  UNIQUE(persona_id, version)
);

CREATE TABLE public.folkly_personas (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  bio_public TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1,
  subject_tags TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL
);

CREATE TABLE public.folkly_pitches (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  persona_id TEXT,
  place TEXT,
  practice TEXT,
  status TEXT NOT NULL DEFAULT 'new',
  score DOUBLE PRECISION,
  reason TEXT,
  created_at TEXT NOT NULL
, slug TEXT, country TEXT, deck TEXT);

CREATE TABLE public.folkly_publication_slots (
  id TEXT PRIMARY KEY,
  slot_date TEXT NOT NULL UNIQUE,
  article_version_id TEXT,
  status TEXT NOT NULL DEFAULT 'open',
  published_at TEXT,
  published_by TEXT,
  note TEXT
);

CREATE TABLE public.folkly_schema_migrations (
  id TEXT PRIMARY KEY,
  applied_at TEXT NOT NULL
);

CREATE TABLE public.folkly_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE public.folkly_sources (
  id TEXT PRIMARY KEY,
  article_version_id TEXT NOT NULL,
  ord INTEGER NOT NULL,
  title TEXT NOT NULL,
  org_author TEXT,
  url TEXT NOT NULL,
  pub_date TEXT,
  retrieved_at TEXT,
  lang TEXT,
  publisher TEXT,
  source_type TEXT,
  independence_rank INTEGER,
  supports_claims TEXT,
  excerpt TEXT,
  UNIQUE(article_version_id, ord)
);

CREATE TABLE public.folkly_spend_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at TEXT NOT NULL,
  run_id TEXT,
  article_slug TEXT,
  step TEXT,
  model TEXT,
  prompt_tokens INTEGER,
  completion_tokens INTEGER,
  cost_usd DOUBLE PRECISION,
  reserved_usd DOUBLE PRECISION
, reservation_id TEXT);

ALTER TABLE public.folkly_article_versions ADD CONSTRAINT folkly_article_versions_article_id_fk FOREIGN KEY (article_id) REFERENCES public.folkly_articles(id);
CREATE INDEX folkly_article_versions_article_id_idx ON public.folkly_article_versions(article_id);
ALTER TABLE public.folkly_assignments ADD CONSTRAINT folkly_assignments_pitch_id_fk FOREIGN KEY (pitch_id) REFERENCES public.folkly_pitches(id);
CREATE INDEX folkly_assignments_pitch_id_idx ON public.folkly_assignments(pitch_id);
ALTER TABLE public.folkly_claim_citations ADD CONSTRAINT folkly_claim_citations_article_version_id_fk FOREIGN KEY (article_version_id) REFERENCES public.folkly_article_versions(id);
CREATE INDEX folkly_claim_citations_article_version_id_idx ON public.folkly_claim_citations(article_version_id);
ALTER TABLE public.folkly_editorial_checks ADD CONSTRAINT folkly_editorial_checks_article_version_id_fk FOREIGN KEY (article_version_id) REFERENCES public.folkly_article_versions(id);
CREATE INDEX folkly_editorial_checks_article_version_id_idx ON public.folkly_editorial_checks(article_version_id);
ALTER TABLE public.folkly_job_steps ADD CONSTRAINT folkly_job_steps_job_id_fk FOREIGN KEY (job_id) REFERENCES public.folkly_jobs(id);
CREATE INDEX folkly_job_steps_job_id_idx ON public.folkly_job_steps(job_id);
ALTER TABLE public.folkly_persona_briefs ADD CONSTRAINT folkly_persona_briefs_persona_id_fk FOREIGN KEY (persona_id) REFERENCES public.folkly_personas(id);
CREATE INDEX folkly_persona_briefs_persona_id_idx ON public.folkly_persona_briefs(persona_id);
ALTER TABLE public.folkly_sources ADD CONSTRAINT folkly_sources_article_version_id_fk FOREIGN KEY (article_version_id) REFERENCES public.folkly_article_versions(id);
CREATE INDEX folkly_sources_article_version_id_idx ON public.folkly_sources(article_version_id);
CREATE TABLE public.folkly_owners (user_id UUID PRIMARY KEY REFERENCES auth.users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
ALTER TABLE public.folkly_publication_slots ADD COLUMN readback_hash TEXT;
ALTER TABLE public.folkly_article_versions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_article_versions FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_article_versions TO service_role;
ALTER TABLE public.folkly_articles ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_articles FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_articles TO service_role;
ALTER TABLE public.folkly_assignments ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_assignments FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_assignments TO service_role;
ALTER TABLE public.folkly_audit_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_audit_events FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_audit_events TO service_role;
ALTER TABLE public.folkly_claim_citations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_claim_citations FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_claim_citations TO service_role;
ALTER TABLE public.folkly_editorial_checks ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_editorial_checks FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_editorial_checks TO service_role;
ALTER TABLE public.folkly_job_steps ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_job_steps FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_job_steps TO service_role;
ALTER TABLE public.folkly_jobs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_jobs FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_jobs TO service_role;
ALTER TABLE public.folkly_media_assets ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_media_assets FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_media_assets TO service_role;
ALTER TABLE public.folkly_page_blocks ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_page_blocks FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_page_blocks TO service_role;
ALTER TABLE public.folkly_persona_briefs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_persona_briefs FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_persona_briefs TO service_role;
ALTER TABLE public.folkly_personas ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_personas FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_personas TO service_role;
ALTER TABLE public.folkly_pitches ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_pitches FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_pitches TO service_role;
ALTER TABLE public.folkly_publication_slots ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_publication_slots FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_publication_slots TO service_role;
ALTER TABLE public.folkly_schema_migrations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_schema_migrations FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_schema_migrations TO service_role;
ALTER TABLE public.folkly_settings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_settings FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_settings TO service_role;
ALTER TABLE public.folkly_sources ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_sources FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_sources TO service_role;
ALTER TABLE public.folkly_spend_ledger ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_spend_ledger FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_spend_ledger TO service_role;
ALTER TABLE public.folkly_owners ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.folkly_owners FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folkly_owners TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.folkly_audit_events_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.folkly_editorial_checks_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.folkly_job_steps_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.folkly_persona_briefs_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.folkly_spend_ledger_id_seq TO service_role;
INSERT INTO public.folkly_settings(key,value,updated_at) VALUES
('production.autonomous_enabled','false',now()::text),
('publication.autonomous_enabled','false',now()::text),
('schedule.enabled','false',now()::text);
COMMIT;
